jooany/ShoesSell

ShoesSell/WebContent/free/ajax_comment_list.jsp, ShoesSell/WebContent/free/detail.jsp, ShoesSell/WebContent/free/list.jsp, ShoesSell/WebContent/free/private/free_comment_delete.jsp, ShoesSell/WebContent/free/private/free_comment_insert.jsp, ShoesSell/WebContent/free/private/free_comment_update.jsp, ShoesSell/WebContent/free/private/free_delete.jsp, ShoesSell/WebContent/free/private/free_insert.jsp, ShoesSell/WebContent/free/private/free_insertform.jsp, ShoesSell/WebContent/free/private/free_update.jsp, ShoesSell/WebContent/free/private/free_updateform.jsp, ShoesSell/src/test/free/dao/FreeCommentDao.java, ShoesSell/src/test/free/dao/FreeDao.java, ShoesSell/src/test/free/dto/FreeCommentDto.java, ShoesSell/src/test/free/dto/FreeDto.java
free 게시판
list.jsp / detail.jsp - 기존의 것 그대로 사용
private 폴더 - 파일명 수정
css 등 추가 수정 필요
free 게시판 댓글
ajax_comment_list.jsp 기존의 것 그대로 사용
private 폴더 - 댓글도 파일명 수정
css 등 추가 수정 필요
=> free 게시판 + 댓글

ShoesSell/WebContent/include/navbar.jsp, ShoesSell/WebContent/index.jsp, ShoesSell/WebContent/users/login.jsp, ShoesSell/WebContent/users/login_form.jsp, ShoesSell/WebContent/users/private/my_page.jsp, ShoesSell/WebContent/users/private/my_pwd_update.jsp, ShoesSell/WebContent/users/private/my_pwd_update_form.jsp, ShoesSell/WebContent/users/private/my_update_form.jsp, ShoesSell/WebContent/users/signup_form.jsp
1. 마이페이지 , 회원가입 폼 , 비밀번호 변경페이지 , 회원수정 변경페이지 navbar 적용
2. 마이페이지 경로 수정
3. .inner CSS 추가
=> Navbar 적용 추가

ShoesSell/WebContent/resell/detail.jsp, ShoesSell/WebContent/resell/list.jsp, ShoesSell/WebContent/resell/private/resell_delete.jsp, ShoesSell/WebContent/resell/private/resell_update.jsp, ShoesSell/WebContent/resell/private/resell_update_form.jsp, ShoesSell/WebContent/resell/private/resell_upload_form.jsp, ShoesSell/src/test/resell/dao/ResellDao.java
=> ResellDao 수정!!

ShoesSell/WebContent/index.jsp, ShoesSell/src/test/filter/LoginFilter.java
Filter 경로에 resell , share , free, user 추가해서 url 이동하는거 확인했습니다. merge 부탁드릴게요.
=> Filter에 resell , share , free , user 경로 추가

ShoesSell/WebContent/share/list.jsp, ShoesSell/src/test/share/dao/ShareDao.java
=> share/list.jsp 오탈자 수정

ShoesSell/WebContent/index.jsp, ShoesSell/WebContent/users/form-validation.css, ShoesSell/WebContent/users/login.jsp, ShoesSell/WebContent/users/login_form.jsp, ShoesSell/WebContent/users/signin.css, ShoesSell/WebContent/users/signup_form.jsp
회원가입 , 로그인 폼 bootstrap 적용 , 로그인 cookie 기능 추가 , 회원가입 form validation 기능
=> 회원가입 , 로그인 폼 bootstrap 적용 , 로그인 cookie 기능 추가 , 회원가입 form validation 기능

ShoesSell/WebContent/index.jsp, ShoesSell/WebContent/share/list.jsp, ShoesSell/src/test/free/dao/FreeDao.java, ShoesSell/src/test/free/dto/FreeDto.java, ShoesSell/src/test/resell/dao/ResellDao.java, ShoesSell/src/test/resell/dto/ResellDto.java, ShoesSell/src/test/share/dao/ShareDao.java, ShoesSell/src/test/share/dto/ShareDto.java
조회수 순 정렬과 rowNum을 위한 게시판 dto,dao 수정 + 세 개 테이블 페이징 처리 완료
=> 조회수 순 정렬과 rowNum을 위한 게시판 dto,dao 수정 + 세 개 테이블 페이징 처리 완료

ShoesSell/WebContent/free/detail.jsp, ShoesSell/WebContent/free/list.jsp, ShoesSell/WebContent/free/private/free_insertform.jsp, ShoesSell/WebContent/free/private/free_updateform.jsp
free 게시판 list, detail, insertform, updateform 수정
=> free 게시판 list, detail, insertform, updateform 수정

ShoesSell/WebContent/users/private/my_page.jsp, ShoesSell/WebContent/users/private/my_update_form.jsp, ShoesSell/WebContent/users/private/offcanvas.css
마이페이지, 회원정보 수정폼 bootstrap 적용완료 (정상작동확인해습니다.)
비밀번호 찾기는 modal로 해결할 예정이고
흠.. 이제 ajax랑 유효성 부족한데 추가할게요~
=> 마이페이지 , 회원정보수정폼 bootstrap 적용 - 정상작동확인, 비밀번호찾기는 Modal로 해결할 예정

ShoesSell/WebContent/share/detail.jsp, ShoesSell/WebContent/share/private/share_delete.jsp, ShoesSell/src/test/share/dao/ShareDao.java
=> share delete기능 설정

ShoesSell/WebContent/share/list.jsp
=> 누락된 title a태그 & 삭제 a 태그 삽입

ShoesSell/WebContent/index.jsp
=> 글자 수 범위 넘어가면 생략 표시

ShoesSell/WebContent/free/detail.jsp, ShoesSell/WebContent/free/list.jsp, ShoesSell/WebContent/free/private/free_insertform.jsp, ShoesSell/WebContent/free/private/free_updateform.jsp, ShoesSell/src/test/free/dao/FreeDao.java
=> free 디자인 수정, dao 문자열오류 수정

ShoesSell/WebContent/users/private/my_ajax_pwd_update.jsp, ShoesSell/WebContent/users/private/my_page.jsp, ShoesSell/WebContent/users/private/my_update_form.jsp
비밀번호 폼 ajax 처리해서 기존거는 삭제 하고 Modal로 변경하였습니다.
수정하기 누르면 Modal이 뜨고 각각의 폼에 유효성 추가
=> 비밀번호 폼 ajax 처리 , 비밀번호 폼 유효성 검사 적용 완료

ShoesSell/WebContent/free/detail.jsp
free detail.jsp 로그인 오류 수정, ui 일부 수정
=> free detail.jsp 로그인 오류 수정, ui 일부 수정

ShoesSell/WebContent/share/detail.jsp, ShoesSell/WebContent/share/private/share_ajax_upload.jsp, ShoesSell/WebContent/share/private/share_upload.jsp, ShoesSell/WebContent/share/private/share_upload_form.jsp, ShoesSell/src/test/share/dao/ShareDao.java, ShoesSell/src/test/share/dto/ShareDto.java
share/private
-share_ajax_upload.jsp 추가
-share_upload_form 수정
-share_upload 수정
=> share update

ShoesSell/WebContent/WEB-INF/table.sql, ShoesSell/WebContent/feed/detail.jsp, ShoesSell/WebContent/feed/list.jsp, ShoesSell/WebContent/feed/private/insert.jsp, ShoesSell/src/test/feed/dao/FeedDao.java, ShoesSell/src/test/feed/dto/FeedDto.java
=> feed 일단 구조만!

ShoesSell/WebContent/share/ajax_comment_list.jsp, ShoesSell/WebContent/share/detail.jsp, ShoesSell/WebContent/share/private/share_comment_delete.jsp, ShoesSell/WebContent/share/private/share_comment_insert.jsp, ShoesSell/WebContent/share/private/share_comment_update.jsp, ShoesSell/src/test/share/dao/ShareCommentDao.java, ShoesSell/src/test/share/dto/ShareCommentDto.java
=> 댓글기능 추가 완료

ShoesSell/WebContent/free/detail.jsp, ShoesSell/WebContent/free/list.jsp
=> free ui 수정, nav 추가

ShoesSell/WebContent/free/detail.jsp, ShoesSell/WebContent/free/list.jsp
=> free 오류 수정

ShoesSell/WebContent/feed/ajax_list.jsp, ShoesSell/WebContent/feed/list.jsp, ShoesSell/src/test/feed/dao/FeedCommentDao.java, ShoesSell/src/test/feed/dao/FeedDao.java, ShoesSell/src/test/feed/dto/FeedCommentDto.java, ShoesSell/src/test/feed/dto/FeedDto.java
feed list 기능 완성
다음 대기 번호 
1. list.jsp의 피드에서 댓글 리스트+특정 영역을 넘어가면 블록을 숨기고 더보기 버튼을 보이게 함+더보기를 클릭하면 보이기
2. 업로드 기능 넣기 
3. ui 디자인 
4. 삭제 기능 넣기
5. 추천 기능 넣기 <- 대공사 예상 // goodCount로
=> feed list 기능 완성

ShoesSell/WebContent/WEB-INF/table.sql, ShoesSell/WebContent/feed/ajax_feed_good.jsp, ShoesSell/WebContent/feed/list.jsp, ShoesSell/WebContent/include/navbar.jsp, ShoesSell/WebContent/index.jsp, ShoesSell/src/test/resell/dao/ResellDao.java
=> reselldao + feed 좋아요 조금 수정

ShoesSell/WebContent/share/detail.jsp, ShoesSell/WebContent/share/list.jsp, ShoesSell/WebContent/share/private/share_ajax_form.jsp, ShoesSell/WebContent/share/private/share_update.jsp, ShoesSell/WebContent/share/private/share_update_form.jsp, ShoesSell/WebContent/share/private/share_upload_form.jsp, ShoesSell/src/test/share/dao/ShareDao.java
=> 일단 이미지 변경까지는 완료

ShoesSell/WebContent/feed/private/ajax_good_delete.jsp, ShoesSell/WebContent/feed/private/ajax_good_insert.jsp
하트(좋아요)버튼 기능 오류상황
하트 버튼을 클릭하여, ajax로 테이블에 행을 추가/삭제 했던 것도 새로고침하면 복구 되는 상황도 랜덤으로 생기고,(정말 sql 테이블에 추가됐다가 갑자기 사라지고 그럽니다..)
피드를 로딩하고 아무렇게나 클릭하다보면 갑자기 어떤 피드는 랜덤으로 이벤트리스너 메소드가 적용이 안됨.. 근데 이런 피드도 랜덤임...................
도대체 이유를 모르겠음.................
=> 하트(좋아요)버튼 기능 오류상황

ShoesSell/WebContent/feed/ajax_list.jsp, ShoesSell/WebContent/feed/list.jsp, ShoesSell/WebContent/feed/private/ajax_good_insert.jsp, ShoesSell/src/test/feed/dao/FeedDao.java
=> lastpage 추가, 좋아요 오류는 동일.

ShoesSell/WebContent/free/detail.jsp, ShoesSell/WebContent/free/list.jsp, ShoesSell/WebContent/free/private/free_updateform.jsp
=> free 페이지 수, 오타 수정

ShoesSell/WebContent/feed/ajax_list.jsp, ShoesSell/WebContent/feed/list.jsp
=> css 일단 수정 완료 /좋아요 못고침

ShoesSell/WebContent/feed/ajax_list.jsp, ShoesSell/WebContent/feed/list.jsp, ShoesSell/WebContent/feed/private/ajax_good_delete.jsp
좋아요 css 및 기능 까지 완료/ insert,delete,댓글 6시까지 해보기
=> 좋아요 css 및 기능 

ShoesSell/WebContent/feed/list.jsp, ShoesSell/WebContent/include/navbar.jsp
=> navbar- 로그인 시, 프로필 사진 추가

ShoesSell/WebContent/users/ajax_signup.jsp, ShoesSell/WebContent/users/private/my_update_form.jsp, ShoesSell/WebContent/users/signup_form.jsp
수점폼에 취소버튼 추가 , 회원가입에도 쿠키삭제 기능 추가
=> 수점폼에 취소버튼 추가 , 회원가입에도 쿠키삭제 기능 추가

ShoesSell/WebContent/share/detail.jsp, ShoesSell/WebContent/share/list.jsp, ShoesSell/WebContent/share/private/share_ajax_upload.jsp, ShoesSell/WebContent/share/private/share_update_form.jsp, ShoesSell/WebContent/share/private/share_upload.jsp, ShoesSell/WebContent/share/private/share_upload_form.jsp
h1- li빼고 삭제
아이디가 동일한경우에만 수정이가능
update에서 수정취소기능 삭제
detail.jsp  max-width 700px max-height 500px 로 수정
share 버튼 크기 크게
제목, 내용, 첨부파일 없을때 alert뜨게 설정
=> h1- li빼고 삭제

ShoesSell/WebContent/free/detail.jsp, ShoesSell/WebContent/free/list.jsp, ShoesSell/WebContent/free/private/free_insertform.jsp, ShoesSell/WebContent/free/private/free_updateform.jsp
=> free 타이틀 변경, param 추가, ui 변경

ShoesSell/WebContent/free/private/free_updateform.jsp
=> 수정확인, 취소 버튼 오류 수정

ShoesSell/WebContent/share/detail.jsp, ShoesSell/WebContent/share/list.jsp, ShoesSell/WebContent/share/private/share_update_form.jsp, ShoesSell/WebContent/share/private/share_upload_form.jsp
=> 검색조건 유지 commit

ShoesSell/WebContent/share/private/share_update_form.jsp
수정할때 파일이미지 첨부안하면 기존이미지로 될수있게 재설정
=> 수정할때 파일이미지 첨부안하면 기존이미지로 될수있게 설정

ShoesSell/WebContent/share/detail.jsp, ShoesSell/WebContent/share/list.jsp, ShoesSell/WebContent/share/private/share_update_form.jsp, ShoesSell/src/test/share/dao/ShareDao.java
=> 최종수정이길 바라면서 pull request

ShoesSell/WebContent/share/detail.jsp, ShoesSell/WebContent/share/private/share_update_form.jsp, ShoesSell/WebContent/share/private/share_upload_form.jsp
진짜 세미플젝 최종 수정(희망)
textarea정렬때문에 손을 댔으나 수정하지 못하고 다시 원상복구
.content{
table-layout: fixed;
word-break: break-all;	
} css추가
개행이 저장이 되는대신에 개행부분을 공란으로 인식해준다.
=> 진짜 세미플젝 최종 수정

ShoesSell/WebContent/share/private/share_delete.jsp
주소창에 강제로 삭제를 입력했을때 삭제가 되어 부분수정 찐막일거에요,,
=> 주소창에 강제로 삭제를 입력했을때 삭제가 되어 부분수정
